# Site settings
name: UX Templates Test Site
title: UX Templates Test Site
email: tsmuse@mozilla.com
description: "Testbed for UX Spec Jekyll templates"
baseurl: "/Firefox-Marketplace-UXSpecs-Templates/templatesTestSite"
url: "https://tsmuse.github.io/Firefox-Marketplace-UXSpecs-Templates/templatesTestSite/"

# Build settings
markdown: kramdown
permalinks: pretty
